DEBUG 2024-08-09 15:22:17.558 UTC: 	 CRAB Client version: v3.240621
DEBUG 2024-08-09 15:22:17.559 UTC: 	 Running on: Linux sbgui3.in2p3.fr 3.10.0-1160.80.1.el7.x86_64 #1 SMP Tue Nov 8 15:48:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux - CentOS Linux 7 (Core)
DEBUG 2024-08-09 15:22:17.559 UTC: 	 Executing command: 'resubmit'
DEBUG 2024-08-09 15:22:17.559 UTC: 	 Found CRAB cache file /home/gcoulon/.crab3
ERROR 2024-08-09 15:22:17.562 UTC: 	 Error: crab_Analysis_2018_HSCPstop_M-1200_CodeV1p0_v1q is not a valid CRAB project directory.
ERROR 2024-08-09 15:22:17.562 UTC: 	 Caught ClientException exception
Traceback (most recent call last):
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 152, in <module>
    client()
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/bin/crab.py", line 135, in __call__
    self.cmd = sub_cmd(self.logger, args[1:])
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/resubmit.py", line 30, in __init__
    SubCommand.__init__(self, logger, cmdargs)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 280, in __init__
    SubCommand.validateOptions(self)
  File "/cvmfs/cms.cern.ch/share/cms/crab-prod/v3.240621.01/lib/CRABClient/Commands/SubCommand.py", line 680, in validateOptions
    raise ConfigurationException(msg)
CRABClient.ClientExceptions.ConfigurationException: [91mError[0m: crab_Analysis_2018_HSCPstop_M-1200_CodeV1p0_v1q is not a valid CRAB project directory.
INFO 2024-08-09 15:22:17.613 UTC: 	 Log file is /opt/sbg/cms/safe1/cms/gcoulon/SaturationEffect/crab.log
